export type HealthIcon = { name: string; label: string };

/** Material Community icon names the live app already renders. */
export const HEALTH_ICONS: HealthIcon[] = [
  { name: "heart-pulse", label: "Heart rate" },
  { name: "heart", label: "Heart" },
  { name: "heart-plus", label: "Heart care" },
  { name: "heart-flash", label: "Pulse" },
  { name: "heart-cog", label: "Cardiology" },
  { name: "stethoscope", label: "Stethoscope" },
  { name: "hospital-building", label: "Hospital" },
  { name: "hospital-marker", label: "Clinic" },
  { name: "ambulance", label: "Ambulance" },
  { name: "medical-bag", label: "Medical bag" },
  { name: "pill", label: "Pill" },
  { name: "pill-multiple", label: "Medicines" },
  { name: "needle", label: "Injection" },
  { name: "syringe", label: "Syringe" },
  { name: "thermometer", label: "Temperature" },
  { name: "bandage", label: "Bandage" },
  { name: "blood-bag", label: "Blood" },
  { name: "dna", label: "DNA" },
  { name: "bacteria", label: "Bacteria" },
  { name: "virus-outline", label: "Virus" },
  { name: "lungs", label: "Lungs" },
  { name: "brain", label: "Brain" },
  { name: "eye", label: "Eye" },
  { name: "ear-hearing", label: "Hearing" },
  { name: "tooth", label: "Dental" },
  { name: "bone", label: "Bone" },
  { name: "stomach", label: "Stomach" },
  { name: "microscope", label: "Lab" },
  { name: "test-tube", label: "Test tube" },
  { name: "flask", label: "Flask" },
  { name: "clipboard-pulse", label: "Vitals" },
  { name: "doctor", label: "Doctor" },
  { name: "mother-nurse", label: "Nurse" },
  { name: "iv-bag", label: "IV drip" },
  { name: "face-mask", label: "Mask" },
  { name: "hand-wash", label: "Hand wash" },
  { name: "hand-heart", label: "Care" },
  { name: "shield-plus", label: "Protection" },
  { name: "shield-cross", label: "Medical shield" },
  { name: "account-heart", label: "Patient" },
  { name: "account-injury", label: "Injury" },
  { name: "dumbbell", label: "Fitness" },
  { name: "weight-lifter", label: "Strength" },
  { name: "run", label: "Running" },
  { name: "walk", label: "Walking" },
  { name: "bike", label: "Cycling" },
  { name: "yoga", label: "Yoga" },
  { name: "meditation", label: "Meditation" },
  { name: "swim", label: "Swimming" },
  { name: "boxing-glove", label: "Boxing" },
  { name: "karate", label: "Martial arts" },
  { name: "arm-flex", label: "Muscle" },
  { name: "human-male-height", label: "Height" },
  { name: "scale-bathroom", label: "Weight" },
  { name: "food-apple", label: "Apple" },
  { name: "food-variant", label: "Meal" },
  { name: "carrot", label: "Vegetables" },
  { name: "fruit-watermelon", label: "Fruit" },
  { name: "fruit-cherries", label: "Berries" },
  { name: "peanut", label: "Nuts" },
  { name: "bread-slice", label: "Grains" },
  { name: "egg", label: "Egg" },
  { name: "fish", label: "Fish" },
  { name: "food-drumstick", label: "Protein" },
  { name: "silverware-fork-knife", label: "Diet" },
  { name: "cup-water", label: "Hydration" },
  { name: "water", label: "Water" },
  { name: "bottle-tonic-plus", label: "Supplements" },
  { name: "tea", label: "Tea" },
  { name: "coffee", label: "Coffee" },
  { name: "nutrition", label: "Nutrition" },
  { name: "sleep", label: "Sleep" },
  { name: "bed", label: "Rest" },
  { name: "power-sleep", label: "Deep sleep" },
  { name: "weather-night", label: "Night" },
  { name: "white-balance-sunny", label: "Daylight" },
  { name: "spa", label: "Spa" },
  { name: "flower", label: "Wellness" },
  { name: "leaf", label: "Natural" },
  { name: "candle", label: "Calm" },
  { name: "hands-pray", label: "Mindfulness" },
  { name: "head-heart", label: "Emotional health" },
  { name: "head-cog", label: "Mental health" },
  { name: "head-snowflake", label: "Cool down" },
  { name: "emoticon-happy-outline", label: "Mood" },
  { name: "emoticon-sick-outline", label: "Illness" },
  { name: "baby-face-outline", label: "Baby" },
  { name: "human-pregnant", label: "Pregnancy" },
  { name: "baby-bottle", label: "Infant feeding" },
  { name: "mother-heart", label: "Mother care" },
  { name: "gender-female", label: "Women's health" },
  { name: "gender-male", label: "Men's health" },
  { name: "human-wheelchair", label: "Mobility" },
  { name: "wheelchair-accessibility", label: "Access" },
  { name: "smoking-off", label: "Quit smoking" },
  { name: "eye-check", label: "Vision check" },
  { name: "toothbrush", label: "Oral care" },
  { name: "mortar-pestle", label: "Pharmacy" },
  { name: "calendar-heart", label: "Checkup" },
  { name: "timer-outline", label: "Routine" },
];

export const LEGACY_CATEGORY_ICONS: Record<string, string> = {
  MdFavorite: "heart-pulse",
  MdFitnessCenter: "dumbbell",
  MdSpa: "flower",
  MdLocalDining: "food-apple",
  MdSelfImprovement: "meditation",
  MdLocalHospital: "hospital-building",
  MdPsychology: "brain",
};

export const categoryIconName = (value?: string) =>
  (value && LEGACY_CATEGORY_ICONS[value]) || value || HEALTH_ICONS[0].name;
